### ISSUE TITLE
Unit tests for XML adapters

### ISSUE THREAD

**Issue by KeyBridge** [KeyBridge/icalendar#2]
The XML adapters in package ietf.params.xml.ns.icalendar.adapter do no appear to successfully *unmarshal* from String to java.time (LocalDate, LocalDateTime, zonedDateTime).

Please write unit tests to confirm forward and reverse functionality of all XML adapters.

**Comment by druzinis** [comment]
Commit a3eb309e0e99802d6e849ff53fb5b1c5acbecafd adds tests and fixes a couple inconsistencies that lead to bugs in the adapters. 

Unsure if the UtcDatetimePropertyType class actually needs ZonedDateTime as the backing class. Perhaps a LocalDateTime with some restrictions in UtcDatetimePropertyType's public API or  OffsetDateTime be better?  
[OffserDateTime javadoc](https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html)

**Comment by KeyBridge** [comment]
Accepted and added a few try/catch to your unit tests.

The ZonedDateTime adapter doesn't to marshal using the correct pattern. However, because all dates are expected at UTC I don't see any requirement for ZonedDateTime in this library at all, do you? Let's instead remove ZonedDateTime entirely and only use LocalDateTime.

**Comment by druzinis** [comment]
Agreed. ZonedDateTime removed with a3fa7824dc76f7f8477b739e0a5ad8b75af0164e.
